In [13]:
import numpy as np
import random

a=np.ndarray((2,3,4))
b=np.ndarray((5,3,4))
print a.shape,b.shape

c = np.concatenate((a, b), axis = 0)
print c.shape

d=np.empty((0,3,4))
e=np.concatenate((a, d), axis = 0)
print e.shape


(2, 3, 4) (5, 3, 4)
(7, 3, 4)
(2, 3, 4)


In [41]:
str='batch'

for i in range(5):
    x=str+'%d' %(i+1)
    print x
    


    

batch1
batch2
batch3
batch4
batch5


In [39]:
a=np.ndarray((2,3,4))
b=np.ndarray((5,3,4))

b[:2,:,:]
e=b[:2,:,:]
d=np.concatenate((a,e))
print e.shape,d.shape

for i in range(3):
    b=np.concatenate((b,a))
    
print b.shape

(2, 3, 4) (4, 3, 4)
(11, 3, 4)


In [48]:
from PIL import Image
m=Image.open('c:/akeshe/image_data/batch1/1_1.png')


a=np.asarray(m)
print a.shape



(200, 200)


In [14]:
import numpy as np
x=np.random.random((12,50,50))
#mask=range(3)
#x=x[mask]
print x.shape
x=np.reshape(x,(x.shape[0],-1))
print x.shape

(12, 50, 50)
(12, 2500)


In [20]:
a=np.array([[2,2],[2,2]])
b=np.array([[3,3]])

print a.shape
print b.shape

c=b-a
print c


(2, 2)
(1, 2)
[[1 1]
 [1 1]]


In [23]:
y=np.empty((5,),dtype="uint8")
x=np.empty((5,),dtype="uint8")

for i in range(5):
    x[i]=i
    y[i]=i

correct_num=np.sum(x==y)

print correct_num
print x
print y



5
[0 1 2 3 4]
[0 1 2 3 4]


In [28]:
num_folds=6
k=10

closest_y=[1,2,4,4,3,5,6,4,3,2]

count=np.zeros((num_folds,))
for i in range(k):
    count[closest_y[i]-1]+=1
print count
last=np.argsort(count)
print (last[num_folds-1]+1)


[ 1.  2.  2.  3.  1.  1.]
4
